### ISSUE TITLE
Doesn't work with nanopool.org?

### ISSUE THREAD

**Issue by Narratheon** [Demion/nodevfee#1]
Hello there,
I tried to integrate your fine piece of software, but unfortunately the DevFee is still going to an address I don't know. 
>05:09:34:993	206c	DevFee: ETH: Stratum - connecting to 'eth-eu1.nanopool.org' <185.71.66.38> port 9999
>05:09:35:040	1b6c	got 39 bytes
>05:09:35:042	206c	send: {"worker": "eth1.0", "jsonrpc": "2.0", "params": ["0x3509F7bd9557F8a9b793759b3E3bfA2Cd505ae31", "x"], "id": 2, "method": "eth_submitLogin"}`

Did I something wrong with the implementation or does your software not work together with nanopool.org? My batch looks like this:

> setx GPU_FORCE_64BIT_PTR 0
> setx GPU_MAX_HEAP_SIZE 100
> setx GPU_USE_SYNC_OBJECTS 1
> setx GPU_MAX_ALLOC_PERCENT 100
> setx GPU_SINGLE_ALLOC_PERCENT 100
> 
> nodevfee.exe
> EthDcrMiner64.exe -epool eth-eu1.nanopool.org:9999 -ewal WALLET/WORKER/EMAIL -epsw x -mode 1 -ftime 10 -di 01234

Im using Claymore 10.0. The -di is not needed anymore, but I guess it won't cause the malfunction?

Kind regards,
Narratheon

**Comment by Demion** [comment]
It should work on nanopool cause it seems to using eth-proxy Ethereum Stratum mode (-esm 0 default). To check if it is working correctly:
1. Check your pool for new default worker.
2. Create nodevfeeLog.txt file and check its logs.
3. Check console for NoDevFee: messages.

Claymore log will show it is mining to its devfee wallet, it is irrelevant.

**Comment by Narratheon** [comment]
Hey there,
I created a log file as you proposed, but it won't be used. I still hits 0 kb. Seems nodevfee won't start at all. I have no idea why - can you help me?

Kind regards,
Narratheon

**Comment by Demion** [comment]
1) Make sure you are using latest stable version - v0.2.1
2) nodevfeeDll.dll and nodevfee.exe should be in same directory as EthDcrMiner64.exe
3) nodevfeeLog.txt should be in same directory as EthDcrMiner64.exe
4) bat should be `nodevfee.exe EthDcrMiner64.exe PARAMETERS`

Latest stable version (v0.2.1) should report any problems by showing message box window with error code.
If it injects and intercepts (hooks) fine and problems are in protocol / packet / pool it should be visible in nodevfeeLog.txt
Not sure how else I can help, maybe Windows Defender / User Access Control or 3rd party Antivirus software block it (although error messagebox should still appear in that case).

**Comment by Narratheon** [comment]
Thanks for the detailed description. Everything is set up like you said. I have absolutely no clue why it is not working. Ill upload my folder tomorrow. Lets see if you can reveal any mistake I might have made.

**Comment by Narratheon** [comment]
Sorry it took so long, this is how my folder looks like:
https://www.dropbox.com/s/i403yr50i4qwo41/Unbenannt.png
As you can see the nodevfeeLog.txt is untouched. I don't get why its not working. I created a "nodevfee.bat" to test whats happening with nodevfee.exe but I don't get any error messages there either. Nothing. Just plain nothing. Do you have any ideas?

**Comment by Demion** [comment]
Everything seems fine, except I see UAC icon on nodevfee.exe, try disable user access control, windows defender and try Run as administrator. Also can you copy paste your entire bat file (to pastebin.com for instance). I see it in first post but I am not sure if it is github message formating or you make new line after nodevfee.exe. If your bat file is wrong it may result in no error.

**Comment by Narratheon** [comment]
It seems you found my problem. The log still hits 0kb but its "last modified" is updated to current date and time. Now I can finally test if this is working for me =) Thanks man!

**Comment by Narratheon** [comment]
Works perfectly! Dual Mining is now an option as you get the full 2% back. Thank you very much Demion, I`ll send you some Ether as small compensation for your effort =)
