### ISSUE TITLE
Does this work for NiceHash and mining Eth?

### ISSUE THREAD

**Issue by up2you1** [Demion/nodevfee#10]
First of all. Thanks for this great tool, Works perfect with CMore v10 miner and mining eth via a pool.

I would like to try use this with nice hash but my only issue is the NH uses a btc address to mine too instead of a eth address. 

I’ve managed to point v10 miner to Nicehash using stratum server and it works fine but I don’t think the nodevfee tool works.

Can anyone confirm ?

Thanks.

**Comment by Demion** [comment]
NiceHash not supported right now.
1. NiceHash needs different approach to injecting NoDevFeeDll.dll in EthDcrMiner64.exe
2. NiceHash, as far as I know, uses different protocol (-esm 3 - nicehash mode) which is also not implemented so far.

**Comment by up2you1** [comment]
Thanks for the information. 

I hope on day it will be :)

Can I ask if the nodevfee works for 10.2 miner too? I’ve read some say it does and some say it doesn’t. 

On that note would you be able to make a same tool for the cryptonight miners aswell?

You are the only dev that alot of people trust so would be great if you could make one. 

Thanks :)

**Comment by Demion** [comment]
It actually does redirect wallet even in 10.6 (latest) but users report some actual efficiency decrease starting from version 10.1 and later (might be some hidden protection). I use 9.7 and ethermine and seems fine.

I never used Cryptonight, may take a look one day, when Ethereum mining wont be profitable. 😆 

I can say though that Equihash (Claymore ZCash AMD Miner). wont be possible to "hack" that way, cause it uses SSL/TLS encryption (as far as I know, it uses encryption for devfee even if you disable it in settings for main connection).

**Comment by Demion** [comment]
duplicate - https://github.com/Demion/nodevfee/issues/3
