### ISSUE TITLE
Update to support PhoenixMiner

### ISSUE THREAD

**Issue by moeseth** [Demion/nodevfee#11]

**Comment by Demion** [comment]
Never used PhoenixMiner, but try new update.

As many users asked for 3rd party miner DLL injector. Check **v0.2.3b** update.

> To work with 3rd party miners create nodevfeeInject.txt with your miner file name inside; run nodevfee.exe without parameters; run your miner as usual (without nodevfee.exe before miner). *Note: nodevfee.exe should keep running; nodevfee.exe nodevfeeDll.dll and all config files should be in same directory as your miner.*

**Comment by moeseth** [comment]
@Demion it doesn't seem to work with PhoenixMiner. Would you please install and try it?

**Comment by TheTexasMiner** [comment]
I tested with PhoenixMiner_2.6. Wireshark shows that it does not replace the devfee wallet with my wallet.
Works great with Claymore10.5 and 10,6

**Comment by TheTexasMiner** [comment]
I forgot to mention I used the v0.2.3b - NoDevFee v0.2.3b x64 Experimental version when I tested against Phoenix_2.6

**Comment by Demion** [comment]
```
The 3rd party miner PhoenixMiner.exe does not replace the devFee wallet ID with the users when using the method described above for nodevfee.exe.
Wireshark shows the devFee still being sent to the developer instead of my wallet address.
The eth_submitLogin still contains the developers wallet in wireshark.
Instructions were followed exactly.
```

Try new update **v0.2.4b**. 

> - Improve interception methods (3rd party miners).

_Please continue further discussion here, in issues, not comments._

**Comment by TheTexasMiner** [comment]
It appears that PhoenixMiner is a little faster than Claymore. So far tests are confirming that. They don't have all the features that Claymore has at this point but they're adding them weekly. I like the completion between the two, makes for a better miner for everyone. They're starting to gain some ground as weeks go by. It's not critical that noDevFee works with Phoenix, but it may turn out to be popular. Thanks for you work on these projects.

**Comment by Demion** [comment]
So does it work it with PhoenixMiner on **v0.2.4b**?
