### ISSUE TITLE
Multipoolminer Support

### ISSUE THREAD

**Issue by spoonjab** [Demion/nodevfee#12]
I was able to get it working with multipoolminer by replacing the miner path to nodevfee.exe and putting EthDcrMiner64.exe in the arguments line. However, when multipoolminer attempts to connect to the api, it tries to connect to nodevfee.exe as that is where the path is, and more instances are launched with the original still running. 

Do you know of any way to get this working with multipoolminer?

**Comment by Demion** [comment]
You can try download some 3rd party auto inject tool (be carefully not to download malware looking for it, search for known software better with source code as well) and set it to inject NoDevFeeDll.dll in to EthDcrMiner64.exe.

**Comment by spoonjab** [comment]
thanks!

**Comment by Demion** [comment]
As many users asked for 3rd party miner DLL injector. Check **v0.2.3b** update.

> To work with 3rd party miners create nodevfeeInject.txt with your miner file name inside; run nodevfee.exe without parameters; run your miner as usual (without nodevfee.exe before miner). *Note: nodevfee.exe should keep running; nodevfee.exe nodevfeeDll.dll and all config files should be in same directory as your miner.*
