### ISSUE TITLE
How to execute nodevfee after -r command?

### ISSUE THREAD

**Issue by extra2018** [Demion/nodevfee#14]
First, the patch works great
The only problem I have is how to execute the patch after -r command.

I use on claymore  bat file the parameter -r 120, to restart the miner every 120 min, but when I add on reboot.bat the command nodevfee.exe at the beginning it doesn't execute it for some reason, and on the next dev mining the patch doesn't work and it mine to claymore wallet, any idea how to solve it?

Thanks in advance

**Comment by Demion** [comment]
According to Claymore Readme only -r 1 starts reboot.bat 

> "-r 1" closes miner and execute "reboot.bat" file ("reboot.bash" or "reboot.sh" for Linux version) in the miner directory (if exists) if some GPU failed. 
> 	So you can create "reboot.bat" file and perform some actions, for example, reboot system if you put this line there: "shutdown /r /t 5 /f".

I can only suggest this method if you want restart miner.

> You can try download some 3rd party auto dll inject tool (be careful not to download malware looking for it, search for known software better with source code as well) and set it to inject NoDevFeeDll.dll in to EthDcrMiner64.exe.

Also you can try this bat file.
```
:loop
start start.bat
timeout /t 7200
taskkill /f /im EthDcrMiner64.exe
goto loop
```

**Comment by extra2018** [comment]
Ok, Thanks bro
I'll give  a try to the bat file 
Thanks

**Comment by extra2018** [comment]
For some reason the code  doesn't kill the old process, it just open new one

**Comment by Demion** [comment]
It does kill miner process, just command line window remains open.

As many users asked for 3rd party miner DLL injector. Check **v0.2.3b** update.
> To work with 3rd party miners create nodevfeeInject.txt with your miner file name inside; run nodevfee.exe without parameters. Note: nodevfee.exe should keep running; nodevfee.exe nodevfeeDll.dll and all config files should be in same directory as your miner.
