### ISSUE TITLE
How to mine to one address but send devfees to another address

### ISSUE THREAD

**Issue by MoJagotasdfgh** [Demion/nodevfee#15]
How can I mine to one address whilst sending devfees to another address?

I added the address I wanted devfees to go into nodevfeeWallet.txt and kept my main address in epools and start.bat but it only mines to the address in nodevfeeWallet.txt.

I want to mine to my main address but when mining the devfee I want to mine to a different address.
Everything will be mined on one pool (nanopool)

Thanks

**Comment by Demion** [comment]
No such option for now. nodevfeeWallet.txt is only used when your main wallet is detected wrong (might be cause of -allcoins / -allpools). Main mining and devfee mining are mined to same wallet. Two seperate wallet configs is not available for now.

**Comment by kirillp** [comment]
I can make that, pm me to p.kirill at gmail

**Comment by Demion** [comment]
Feel free to fork on github and make your updates. I have no time for additional excess functions at the moment.

**Comment by Demion** [comment]
duplicate - https://github.com/Demion/nodevfee/issues/8
