### ISSUE TITLE
create process error#2

### ISSUE THREAD

**Issue by flatounet** [Demion/nodevfee#16]
i tryed it with claymore 10.6
and i got this popup from nodevfee ..

"create process error#2"

( windows 10 64 nvidia card )

( can you specify witch nodevfee work with witch claymore ? )
at this time my last nodevfee work with claymore 10.2 ....

nodevfee for lastest update was welcome

**Comment by Demion** [comment]
> ERROR_FILE_NOT_FOUND
> 2 (0x2)
> The system cannot find the file specified.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

Your bat is probably wrong. nodevfee.exe & nodevfeeDll.dll should be in same directory as miner (EthDcrMiner64.exe)

**Comment by flatounet** [comment]
yes i dont have remove a old line in bat ....
my mistake ....
yes friend give me same feedback i have to use claymore 10.0

ethermine = claymore   or a  claymore is a fork ?
better minning  ethermine(9.7) + proxy ?

**Comment by Demion** [comment]
ethermine.org is pool for mining Ethereum. You can mine whatever you want, use any Claymore and test yourself what is better for you. If you see messages in Claymore miner console `NoDevFee: `then patch is working, actual results check on your pool. I prefer using 9.7, but 10.0 should be fine too, you can try 10.5 / 10.6 as well.
