### ISSUE TITLE
auth_method injection

### ISSUE THREAD

**Issue by tradada** [Demion/nodevfee#17]
Hi Demion,

I'd like to ask you about option for pool redirection from a file to my own.
It works fine only if it has the same auth method as the "picked" devfee pool later in the miners process, from which it redirects (ESM 0 / ethSubmit_login in general):
![devfee_auth_method](https://user-images.githubusercontent.com/36152062/35796150-d9a3171c-0a5b-11e8-8507-ce8ad59c7265.jpg)
). 
As you see it timeouts until the "right" pool is picked from the list (with the same method used as pool we redirect to). Apparently it means nodevfee auth method is based on "picked" pool, but it is correct when you start the script, however it seems later it's ignored:
![devfee_auth_method2](https://user-images.githubusercontent.com/36152062/35797404-e48f9e08-0a5f-11e8-9399-8acb1e11e91a.jpg)

I can't describe it more, because I don't understand technical part.

Is it possible to always inject only auth method based on my preference / on pool I want to redirect"? Like a new config file? Or any ideas how to fix this please?

Thanks.

**Comment by Demion** [comment]
As far as I understand, devfee use different pools and different -esm 0 / -esm 1 according to each pool. Only thing you can do is use pool which accept both protocols (like ethermine for instance) or you can try forcefuly set -esm 0 or -esm 1 in your bat file, but that might not help, no other solution so far.

**Comment by Demion** [comment]
Further discussion here - https://github.com/Demion/nodevfee/issues/19
