### ISSUE TITLE
Useless for mining altcoins (anycoin different than ethereum)

### ISSUE THREAD

**Issue by rvsh2** [Demion/nodevfee#25]
Dev fee is mined only on ethereum and use ethereum DAG so need ethereum wallet. If I mine some altcoin eg. ELLAISM ora PIRL ora AKROMA then nodevfee use ELLAISM&etc. wallet address on ethereum pool for example on ethermine.org. I can see my ellaism address on ethermine.org with 'default' worker and hashrate that I missed.

Please add mining dev fee to wallet in nodevfeewallet.txt and mining normal to adress specified in config.txt or command line. That should fix the main issue of this app.

Will donate if you do. 
Thanks!

**Comment by Demion** [comment]
You can try `nodevfeePools.txt` and try redirect ethermine.org to your altcoin pool. If that does not help, then no solution so far. Read more about that on main page README.

**Comment by rvsh2** [comment]
I tried it and it worked but only when dev fee 'is mined' from dwarfpool. Other pools has somekind of authorisation failure.

I normally use remote managment to change coins (many rigs) - in this case above solution is very time consuming.

Thanks for advice.

**Comment by rvsh2** [comment]
I use config.txt:
# WARNING! Remove "#" characters to enable lines, with "#" they are disabled and will be ignored by miner! Check README for details.
# WARNING! Miner loads options from this file only if there are not any options in the command line!

-dbg -1
-r 1
-minspeed 190
-mport 3005
-mpsw xxx
-mode 1 
-ftime 10
-tstop 85
-tt 60
-fanmin 85
-fanmax 100
-cclock 1050,1050,1150,1150,1150,1050,1150
-mclock 2050,2050,2050,2100,2050,2050,2100
-cvddc 870,870,870,870,870,870,870
-mvddc 885,885,885,885,885,885,885
-powlim -20,-20,-20,-20,-20,-20
-dcri 1
-allcoins -1
-asm 2
-retrydelay 1


'Retrydelay 1' is a must in this case.

**Comment by Demion** [comment]
Authorization problem is common and cause is your pool only supports one of protocols (ESM 0 or ESM 1) and devfee switches protocols randomly. So your only solution is to try another pool or just leave as is. More discussion here - https://github.com/Demion/nodevfee/issues/19
