### ISSUE TITLE
nodevfeeWallet.txt not working correctly for non standard username (eth address)

### ISSUE THREAD

**Issue by Techn1cks** [Demion/nodevfee#27]
As title states, nodevfeeWallet.txt is not working correctly for non standard username (eth address).

Scenario:
nodevfeeWallet.txt contains eth address to be used during devfee
Pool being mined - username is NOT eth address - let's assume address is Non-eth-format-user
allpools option is ON

At startup, it shows the wallet set into the nodevfeeWallet.txt - so far so good.
Then the miner sends this (from log file): 
send: {"id":2,"jsonrpc":"2.0","method":"eth_login","params":["Non-eth-format-user","x"]}
Then you get:
Job timeout, disconnect, retry in 5 sec...

However, without the nodevfeeWallet.txt it detects this: 
NoDevFee: eth_login -> Non-eth-format-user","x"]}
Yes, it is formatted just as you see above, i didn't add any ] or } after. 

It still works, but logins to devfee pools fail (it still mines during this time on my pool) - and after about 2 hours of failures, miner goes into "free" mining mode, lowering its speed - right now i have a script that reboots the miner every hour, but that's still time lost. This is what made me try to use the nodevfeeWallet.txt and it doesn't seem to work.

On normal pools with eth address login it works, showing something like this instead of the eth_login shown above (here we see eth_submitLogin)
NoDevFee: eth_submitLogin -> 0x51443253454525125231523523215352352e23

**Comment by Demion** [comment]
Non ETH address logins are not supported in any way (only ESM 0 and ESM 1 are supported for now).

By default nodevfee records first login address as your main wallet and then replace all following logins (usually devfee, but can also be main after disconnect) with this wallet address.
`nodevfeeWallet.txt` is only needed in rare cases when your main wallet is not recorded correctly, this may happen when you mine alt coin / fork and miner first login to devfee wallet and only after that start to mine your alt coin.
`nodevfeeWallet.txt` is not for non ETH login support nor to seperate main wallet and devfee wallet outputs.
