### ISSUE TITLE
PhoenixMiner 2.6 problems

### ISSUE THREAD

**Issue by P-D-A** [Demion/nodevfee#29]
Hello!
Thank you so much for your work.
There is a problem with the interception in Phoenix Miner 2.6
More precisely, only the first two DevFee connections are intercepted
Next, the pool and wallet address is used by the developer Phoenix Miner 2.6
Used NoDevFee v0.2.4b x64 Experimental, nodevfeeInject.txt, nodevfeePools.txt, nodevfeeWallet.txt

A huge request to pay attention to [Phoenix Miner 2.6](https://bitcointalk.org/index.php?topic=2647654.0)

Thank you!

**Comment by Demion** [comment]
1. Create empty text file `nodevfeeLog.txt` in miner directory.
2. Run it until problem occurrs.
3. Upload here Phoenix Miner log and `nodevfeeLog.txt` here.

**Comment by P-D-A** [comment]
Hello!
[nodevfeeLog.txt](https://github.com/Demion/nodevfee/files/1723037/nodevfeeLog.txt)
[nodevfeePools.txt](https://github.com/Demion/nodevfee/files/1723040/nodevfeePools.txt)
[PhoenixMiner.txt](https://github.com/Demion/nodevfee/files/1723041/PhoenixMiner.txt)
![2018-02-14 at 10 33 29](https://user-images.githubusercontent.com/20209313/36192558-18fffa24-1173-11e8-8cf0-8ab1e33adbfc.jpeg)
![2018-02-14 at 10 33 29_2](https://user-images.githubusercontent.com/20209313/36192559-191a822c-1173-11e8-9e75-c8a40bf83e1c.jpeg)

**Comment by Demion** [comment]
Wallet redirection seems ok, but pool redirection does not work for some reason.
Can you provide your bat file so that I can test on my end easier.

**Comment by P-D-A** [comment]
```
@echo off
TIMEOUT /T 60
set GPU_FORCE_64BIT_PTR 1
set GPU_MAX_HEAP_SIZE 100
::setx GPU_USE_SYNC_OBJECTS 1
set GPU_MAX_ALLOC_PERCENT 100
set GPU_SINGLE_ALLOC_PERCENT 100
@echo on
PhoenixMiner.exe
```

[config.txt](https://github.com/Demion/nodevfee/files/1723199/config.txt)

**Comment by Demion** [comment]
I created debug version to try help figure out what is the problem. It may be unstable. 
I will be interested in logs after test.
[NoDevFee_v0.2.5a_x64.zip](https://github.com/Demion/nodevfee/files/1723317/NoDevFee_v0.2.5a_x64.zip)

**Comment by P-D-A** [comment]
For what period you need the log ?
3-6 hours will be enough ?

**Comment by Demion** [comment]
Longer better, need to catch moment when connection (pool) redirection fail.

**Comment by kirillp** [comment]
Он заменяет адрес но не заменяет сервер походу
Вот обычный логин (на etherdig.net)

s = 0x04BC sin_family = 0x0002 sin_addr = 190.115.26.22 sin_port = 8008 namelen =   16
s = 0x04BC flags = 0x0000 len =  128 buf = 7B 22 69 64 22 3A 31 2C 22 6A 73 6F 6E 72 70 63 22 3A 22 32 2E 30 22 2C 22 6D 65 74 68 6F 64 22 3A 22 65 74 68 5F 73 75 62 6D 69 74 4C 6F 67 69 6E 22 2C 22 77 6F 72 6B 65 72 22 3A 22 68 6F 6D 65 22 2C 22 70 61 72 61 6D 73 22 3A 5B 22 30 78 65 35 61 34 32 35 36 33 34 33 32 65 66 65 31 37 37 34 66 38 37 34 32 33 35 37 30 62 34 38 63 64 36 31 38 31 66 32 34 66 22 2C 22 78 22 5D 7D 0A 
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"home","params":["0xe5a42563432efe1774f87423570b48cd6181f24f","x"]}

А вот дев фии:

s = 0xB0E0 sin_family = 0x0002 sin_addr = 13.228.161.243 sin_port = 4444 namelen =   16
s = 0xB0E0 flags = 0x0000 len =  130 buf = 7B 22 69 64 22 3A 31 2C 22 6A 73 6F 6E 72 70 63 22 3A 22 32 2E 30 22 2C 22 6D 65 74 68 6F 64 22 3A 22 65 74 68 5F 73 75 62 6D 69 74 4C 6F 67 69 6E 22 2C 22 77 6F 72 6B 65 72 22 3A 22 65 74 68 31 2E 30 22 2C 22 70 61 72 61 6D 73 22 3A 5B 22 30 78 65 35 61 34 32 35 36 33 34 33 32 65 66 65 31 37 37 34 66 38 37 34 32 33 35 37 30 62 34 38 63 64 36 31 38 31 66 32 34 66 22 2C 22 78 22 5D 7D 0A 
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0xe5a42563432efe1774f87423570b48cd6181f24f","x"]}

тут видно что кошелек заменен, но адрес пула нет.
Вот мой nodevfeePools.txt

[nodevfeePools.txt](https://github.com/Demion/nodevfee/files/1723837/nodevfeePools.txt)

**Comment by kirillp** [comment]
так же есть подтверждение сервера о том что я туда слал свой дев фии
https://ethermine.org/miners/e5a42563432efe1774f87423570b48cd6181f24f

**Comment by P-D-A** [comment]
@Demion 
NoDevFee_v0.2.5a_x64.zip
in this version made additional changes?
On the version NoDevFee_v0.2.5a, I can not reproduce the error.
5 interceptions worked well

**Comment by P-D-A** [comment]
Russian-speaking?
Еще раз Спасибо за вашу работу 
Завтра скину лог посмотрим что да как

**Comment by P-D-A** [comment]
@Demion 
Одно смущает
У меня задан адрес 29.ip-5-196-13.eu 9999 (5.196.13.29:9999)
А NoDevFee подставляет рандомный хост из eth-eu2.nanopool.org
```
host[0] = 149.202.42.174:9999
host[1] = 151.80.144.188:9999
host[2] = 5.196.26.96:9999
host[3] = 51.255.34.79:9999
host[4] = 51.255.34.80:9999
host[5] = 92.222.10.59:9999
s = 0x1CBB0 sin_family = 0x0002 sin_addr = 51.255.34.79 sin_port = 9999 namelen =   16
```

**Comment by Demion** [comment]
Нужен весь лог файл, так трудно понять.

**Comment by P-D-A** [comment]
@Demion 
[nodevfeeLog.txt](https://github.com/Demion/nodevfee/files/1724238/nodevfeeLog.txt)

**Comment by Demion** [comment]
[NoDevFee_v0.2.5.1a_x64.zip](https://github.com/Demion/nodevfee/files/1724327/NoDevFee_v0.2.5.1a_x64.zip)

**Comment by P-D-A** [comment]
Отработал DevFee но ситуация не изменилась
[nodevfeeLog.txt](https://github.com/Demion/nodevfee/files/1724379/nodevfeeLog.txt)

**Comment by Demion** [comment]
Судя по логу у вас в  `nodevfeePools.txt` вторая строчка (основной пул) - `eth-eu2.nanopool.org 9999`
`Pools[0] = eth-eu2.nanopool.org:9999`

**Comment by P-D-A** [comment]
Да вы правы
по ошибки подмахнул строчку

**Comment by babbage2018** [comment]
Объясните пожалуйста как правильно заполнить nodevfeePools.txt

**Comment by Demion** [comment]
> `nodevfeePools.txt` должен содержать список devfee пулов, которые нужно перенаправлять. (первая строка кол-во записей (включая основной пул), вторая строка - основной пул, далее список devfee пулов) Сделано так, что нужно вручную указывать список devfee пулов, иначе будет перенаправлять вторую монету (sia, dcr и т.п. если используется).

**Comment by babbage2018** [comment]
Спасибо, если майнить соло, только эфир, нужно ли добавлять дэфи пулы?

**Comment by P-D-A** [comment]
@babbage2018 
Есть же пример 
https://pastebin.com/bWd1QAAe
Поменяйте 2 стройки и в путь

**Comment by babbage2018** [comment]
я именно этот пример и использую, просто когда не понимаю, что и для чего ищу ответы на вопросы

**Comment by Demion** [comment]
Не понял суть вопроса, devfee майнит только эфир, вторую монету не надо добавлять (SIA, DCR и т.п.). На счет форков, альтов на ethhash не знаю, но по-моему devfee все равно будет майнить только эфир (но перенаправление должно все равно сработать т.к. протокол у пулов одинаковый, насколько я знаю), так что все равно те-же пулы. Можно понаблюдать за майнером куда он подключается на devfee и те пулы внести в файл. Автоматически это сделать пока не получается, только через список в ручную. В том примере все (или почти все) используемые devfee пулы.

**Comment by babbage2018** [comment]
Спасибо.

**Comment by P-D-A** [comment]
@Demion 
Предварительно все работает норм
Спасибо
[nodevfeeLog.txt](https://github.com/Demion/nodevfee/files/1724466/nodevfeeLog.txt)
кинь свой номер тел на pdawintest@gmail.com
с меня на пиво

**Comment by P-D-A** [comment]
@babbage2018 
Не хорошо так делать 
Я ваш номер тел не просил

**Comment by babbage2018** [comment]
я не сразу понял) пришло на почту письмо и предложение выпить пиво) я и ответил) сорян, буду внимательнее)

**Comment by kirillp** [comment]
> Автоматически это сделать пока не получается, только через список вручную.

Можно эти новые нераспознанные пулы скидывать в какойто файлик

**Comment by P-D-A** [comment]
@kirillp 
[nodevfeePools.txt](https://github.com/Demion/nodevfee/files/1724761/nodevfeePools.txt)
Актуален для PhoenixMiner (заменить 2 строчку)
других адресов я не замечал

**Comment by Demion** [comment]
Вместо `:` между адресом и портом должен быть пробел, иначе работать не будет!
Автоматически распознать не получится, т.к. не определить разницу между пулом дуал монетки (если используется) и devfee пулом.
Список на главной странице ReadMe (pastebin) актуален.
Нужно просто вставить после первой строчки ваш пул и удостовериться, что первая строчка соответствует кол-ву записей (строк) в файле.

**Comment by P-D-A** [comment]
Поправил + добавил пару адресов
[nodevfeePools.txt](https://github.com/Demion/nodevfee/files/1724914/nodevfeePools.txt)
Актуален для PhoenixMiner (заменить 2 строчку)

**Comment by P-D-A** [comment]
@Demion 
Посмотрел лог за 10 часов 
Все четко отрабатывает
Обновил

**Comment by rzrwolf** [comment]
Аналогично, вроде бы стал отрабатывать. На нанопуле воркер eth1.0 стабильно появляется. До этого отсылал 2 раза шары и больше не появлялся.

**Comment by P-D-A** [comment]
@rzrwolf 
Nanopool совсем плохой стал 
Особенно кошелек раздувается с каждым днем сильнее и сильнее
https://etherscan.io/address/0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5

**Comment by P-D-A** [comment]
@Demion 
Вопрос не по теме 
eth proxy или qtminer что лучше использовать для ethermine ?

**Comment by kirillp** [comment]
etherdig.net/#/account/0xe5a42563432efe1774f87423570b48cd6181f24f

У меня не появляется воркера, что-то я делаю не так

**Comment by P-D-A** [comment]
что такое ID 0 ?

**Comment by kirillp** [comment]
Это NoDevFee от клеймора, у меня только 2 фермы экспериментально на Фениксе

**Comment by P-D-A** [comment]
Что вы хотите найти (ищите) ?
id 0 это и есть но NoDevFee

**Comment by P-D-A** [comment]
> должен быть eth1.0
не обязательно

**Comment by kirillp** [comment]
очень странно, должно быть все ок, вот выжимка из лога за ночь 
find /n "submitLogin" nodevfeeLog.txt  > submitLogin.txt
find /n "sin_family" nodevfeeLog.txt  >> submitLogin.txt
[submitLogin.txt](https://github.com/Demion/nodevfee/files/1727237/submitLogin.txt)

может пул не поддерживает имена воркеров с точками ? 
буду изучать

**Comment by Demion** [comment]
А с чего вы взяли, что на пуле должен сразу появиться воркер. Там может быть задержка с обновлением, и вообще, например, когда во время devfee шар не найдено, то он может не быть добавлен. 
Не знаю по поводу других пулов, но на ethermine выглядит следующим образом - https://ethermine.org/miners/cb4effdeb46479caa0fef5f5e3569e4852f753a2. 
Думаю это нормально, лог выглядит в порядке. 
Ethermine поддерживает 2 протокола, разницы думаю нет.

**Comment by kirillp** [comment]
Я поверил, поставил основной воркер как Eth1.0 и машина с моего пула пропала
Щас напишу плагинчик который уберет точки с воркеров, и тогда посмотрю что получится.

**Comment by kirillp** [comment]
Админ нашего пула подтвердил что "." нельзя в воркерах использовать.
Заменил точки на подчерки. Будем посмотреть.
https://github.com/kirillp/nodevfee/commit/d701194ccfa9f0b7f54ab135c3c20b85114c087b

**Comment by ilovelobster** [comment]
Hi Demion,

Thanks for the nifty program, but running into a little issue here:
Version: https://github.com/Demion/nodevfee/files/1724327/NoDevFee_v0.2.5.1a_x64.zip

I've ran it twice, first time (Run A) intercepted once and then restarted miner (Run B). As you can see Run B ran in the first hour but the subsequent hours did not get intercepted. I kept it on for a couple more hours and it seems to have worked in twice.

Graph - https://imgur.com/a/5ccBE
Chart - https://imgur.com/8lQO0vr

**Comment by P-D-A** [comment]
@ilovelobster 
Use https://github.com/Demion/nodevfee/releases/tag/v0.2.5b

**Comment by P-D-A** [comment]
@ilovelobster 
Use https://github.com/Demion/nodevfee/releases/tag/v0.2.5b

The minimum complexity of the nanopool is 10,000 MH
DevFee can not always catch a share
nanopool = 10 000MH
ethermine = 4000MH
dwarfpool = 2000MH

**Comment by ilovelobster** [comment]
Thanks @P-D-A

**Comment by Demion** [comment]
Need logs (claymore log and nodevfeeLog.txt) to check if it is working correctly.
In my opinion mining is not strictly deterministic - difficulty increases, there is share find luck, pools also differs, there might be some hidden protection algorithms in new versions of miners.
Only I can check is if interception (on network packet level) and wallet / connection redireciton is functioning correctly (need logs for that).

By the way v0.2.5b is mostly v0.2.5abut without extensive logging and with cleaned code, no new functionality. But v0.2.5b is still prefered.

**Comment by ilovelobster** [comment]
Will run for a few hours - will report back.

**Comment by kirillp** [comment]
After testing: my patch does not help, all eth_submitWork packets **must have** correct worker id.
I will try to replace the eth_submitWork with one with worker field.

**Comment by kirillp** [comment]
Very good. I finally made it work. I add worker if it not preset. 
I teste it on my 3 farms on Phoenix and 1 farm on Claymore. It works perfectly.
The code is on my branch. Pease review and merge.

**Comment by P-D-A** [comment]
@kirillp 
Можешь выложить свою версию ?

**Comment by ilovelobster** [comment]
@Demion 

A huge dump of log for ya! Ran for 12hours+

Version: v0.2.5b 
Screenshot: ![image](https://user-images.githubusercontent.com/31752519/36307261-56bf8f38-12e9-11e8-8d71-55b6fd6792e3.png)

[nodevfeeLog.txt](https://github.com/Demion/nodevfee/files/1731254/nodevfeeLog.txt)
[log20180215_073645.txt](https://github.com/Demion/nodevfee/files/1731255/log20180215_073645.txt)

**Comment by Demion** [comment]
```
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4.KingKong/kamnong+nanopool@gmail.com","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}
{"id":1,"jsonrpc":"2.0","method":"eth_submitLogin","worker":"eth1.0","params":["0x1ca59550b45745b386b2ddfD5c394E96097F2ab4","x"]}

s = 0x052C sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0B74 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0B5C sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BB4 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BE0 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BC4 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0470 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BA0 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0B3C sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BC4 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x046C sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
s = 0x0BD0 sin_family = 0x0002 sin_addr = 5.196.13.29 sin_port = 9999 namelen =   16
```
Looks good.

**Comment by P-D-A** [comment]
@kirillp 
Very good. I finally made it work. I add worker if it not preset.
I teste it on my 3 farms on Phoenix and 1 farm on Claymore. It works perfectly.
The code is on my branch. Pease review and merge.

С вашими правками увеличилось количество stale share достаточно значительно
Ранее за сутки не превышало 2-3шт на версии (@Demion NoDevFee_v0.2.5b)
Сегодня за 4 часов более 15 старых шар

**Comment by kirillp** [comment]
У меня 1.4% stale, мои правки нужны только для пула etherdig, если без моих пул видит дев фии то не надо мою версию использовать.  еще логгинг может тормозить. дописывалка worker - врядли создаёт задержку

**Comment by serjkru** [comment]
Доброго времени суток.

Подскажите пожалуйста как мне запустить PhoenixMiner с текущей таблеткой?
Интересует где мне прописать воркера для отправки ДевФии. Спасибо!

**Comment by Rocket31337** [comment]
I'm still having the issue with Phoenix mining to the correct address but wrong server. Is there any updates on a fix? I tried the file as the readme states but its still mining to the wrong location.

**Comment by Demion** [comment]
@serjkru нет такой функции, воркер на пуле будет пустой или default и т.п.

@Rocket31337 Without logs and more detailed information, can not help.
