### ISSUE TITLE
How to read the log?

### ISSUE THREAD

**Issue by PeshBG** [Demion/nodevfee#30]
I have trouble reading the log. can you please add some examples on how to understand its content?

**Comment by Demion** [comment]
What log? `nodevfeeLog.txt`? 
It is debug log to troubleshoot issues.
Although it is raw copy of all connections to pools and data sent via network packets. 
You may be interested in searching for keyword sin_addr for pool connections and `eth_submitLogin` or `eth_Login` for authorization packets (devfee wallet redirection).

**Comment by PeshBG** [comment]
Thank you
