### ISSUE TITLE
OpenProcess error #5

### ISSUE THREAD

**Issue by Mac2100** [Demion/nodevfee#32]
Hi, Thank you for all your work!
Im getting an odd error as soon as i start the miner. (using phoenix Miner 2.6 with 2.5b)
"OpenProcess error #5"

any idea what i did wrong?

<img width="1440" alt="screen shot 2018-02-22 at 3 02 01 pm" src="https://user-images.githubusercontent.com/28598771/36561860-0c09502e-17e3-11e8-9838-8f0f9656d074.png">

**Comment by Mac2100** [comment]
Still seems to work even with the error window open?

<img width="1440" alt="screen shot 2018-02-22 at 3 21 34 pm" src="https://user-images.githubusercontent.com/28598771/36562179-2c475380-17e4-11e8-8fd3-409bdb2c0df5.png">

**Comment by babbage2018** [comment]
@Mac2100 name must match with exe name, rename nodevfeeDll.dll to nodevfee.dll or any other name example.exe example.dll

**Comment by Mac2100** [comment]
Thanks for the reply!
Ive tried a few different things - and this is the only way I can get it to run (WITH error #5)
May I see a screenshot of your miner folder?

<img width="883" alt="screen shot 2018-02-22 at 8 57 49 pm" src="https://user-images.githubusercontent.com/28598771/36574495-09e9a3b2-1814-11e8-950a-5a02b465b939.png">

**Comment by Demion** [comment]
I see this error from time to time too, but injection still works. Trying to figure out what is the cause.
> **ERROR_ACCESS_DENIED**
> 5 (0x5)
> Access is denied.
