### ISSUE TITLE
Failed to build nodevfee.dll

### ISSUE THREAD

**Issue by newtoopensuse** [Demion/nodevfee#36]
Hi,

   First of all, I am not a programmer but I thought I should play it safe and compile the program. I am running visual studio 2015 community edition, version 14 update 3, Windows 7pro x64.
    nodevfee.exe built fine, but nodevfee.dll failed to build with these errors:

1>------ Build started: Project: nodevfeeDll, Configuration: Debug x64 ------
1>  main.cpp
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(47): warning C4996: '_swprintf': This function or variable may be unsafe. Consider using _swprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h(1444): note: see declaration of '_swprintf'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(122): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2238): note: see declaration of 'gethostbyname'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(134): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(2238): note: see declaration of 'gethostbyname'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(164): warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
1>  c:\program files (x86)\windows kits\8.1\include\um\winsock2.h(1868): note: see declaration of 'inet_ntoa'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(233): warning C4996: 'wcscpy': This function or variable may be unsafe. Consider using wcscpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstring.h(121): note: see declaration of 'wcscpy'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(240): warning C4996: 'wcscpy': This function or variable may be unsafe. Consider using wcscpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstring.h(121): note: see declaration of 'wcscpy'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(252): warning C4996: 'wcscpy': This function or variable may be unsafe. Consider using wcscpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstring.h(121): note: see declaration of 'wcscpy'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(254): warning C4996: 'wcscat': This function or variable may be unsafe. Consider using wcscat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstring.h(101): note: see declaration of 'wcscat'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(272): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h(129): note: see declaration of '_wfopen'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(278): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h(129): note: see declaration of '_wfopen'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(285): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h(129): note: see declaration of '_wfopen'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(299): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\corecrt_wstdio.h(129): note: see declaration of '_wfopen'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(303): warning C4996: 'fscanf': This function or variable may be unsafe. Consider using fscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1193): note: see declaration of 'fscanf'
1>c:\users\xx\desktop\nodevfee-0.2.6b\nodevfeedll\source\main.cpp(306): warning C4996: 'fscanf': This function or variable may be unsafe. Consider using fscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1193): note: see declaration of 'fscanf'
1>  trampoline.c
1>  hook.c
1>  hde64.c
1>  hde32.c
1>  buffer.c
1>  Generating Code...
1>main.obj : error LNK2019: unresolved external symbol __imp_htons referenced in function "void __cdecl OnConnect(unsigned __int64,struct sockaddr const *,int)" (?OnConnect@@YAX_KPEBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_inet_ntoa referenced in function "void __cdecl OnConnect(unsigned __int64,struct sockaddr const *,int)" (?OnConnect@@YAX_KPEBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_ntohs referenced in function "void __cdecl OnConnect(unsigned __int64,struct sockaddr const *,int)" (?OnConnect@@YAX_KPEBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_gethostbyname referenced in function "void __cdecl OnConnect(unsigned __int64,struct sockaddr const *,int)" (?OnConnect@@YAX_KPEBUsockaddr@@H@Z)
1>C:\Users\xx\Desktop\nodevfee-0.2.6b\x64\Debug\nodevfeeDll.dll : fatal error LNK1120: 4 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Demion** [comment]
Select Release x64 Build.

**Comment by newtoopensuse** [comment]
Thank you very much. Did as you said and changed platform toolset to visual studio 2015 and it worked.
