### ISSUE TITLE
Doesn't work with allpools (Login.WorkerName)

### ISSUE THREAD

**Issue by ax-webwarren** [Demion/nodevfee#4]
Tried with supernova pool:

DevFee: ETH: Stratum - connecting to 'us1.ethermine.org' <192.95.30.210> port 4444
NoDevFee: connect -> eth.suprnova.cc:5005
NoDevFee: eth_login -> ***********************", "x"], "id": 2, "met
DevFee: ETH: Stratum - Connected (us1.ethermine.org:4444)
Socket was closed remotely (by pool)
DevFee: ETH: Job timeout, disconnect, retry in 20 sec...

**Comment by ax-webwarren** [comment]
happens on miningpoolhub and suprnova

**Comment by Demion** [comment]
Seems like devfee at ethermine use eth_login (-esm 1) and Suprnova / Mining Pool Hub only supports eth_submitLogin (-esm 0) or vice versa. Try directly set option -esm 0 (or -esm 1) for miner.

**Comment by ax-webwarren** [comment]
Can we add a worker name or additional field for login name in wallet.txt?
Now it rejects shares for dev fee.
Although it connects.

**Comment by Demion** [comment]
-eworker option is supported starting from v0.2.2b. If you mean separatly directly name devfee worker then that seems unnecessary complication for now. I dont entirely understand what you trying to achieve with that. I need full log and bat files to be able to try help.

**Comment by ax-webwarren** [comment]
I'm trying to send the devfee shares to dwarfpool while mining on miningpoolhub

DevFee: ETH: Stratum - connecting to 'us1.ethermine.org' <149.56.26.221> port 4444
NoDevFee: connect -> eth-eu.dwarfpool.com:8008
NoDevFee: eth_login -> 0x0bf8225009794d30be8c3e81956ac77adff4bb54
DevFee: ETH: Stratum - Connected (us1.ethermine.org:4444)
ETH: Authorization failed
: {"id":2,"jsonrpc":"2.0","result":false}
Stratum - reading socket failed 10038, disconnect
DevFee: ETH: Job timeout, disconnect, retry in 20 sec...

Btw, how would be the config if eworker would be used?
And also mining from miningpoolhub and sending the devfee to miningpoolhub doesn't submit the shares.

s = 0x04D0 sin_family = 0x0002 sin_addr = 192.81.129.199 sin_port = 20536 namelen =   16

s = 0x04D0 flags = 0x0000 len =  106 buf = 7B 22 69 64 22 3A 32 2C 22 6A 73 6F 6E 72 70 63 22 3A 22 32 2E 30 22 2C 22 6D 65 74 68 6F 64 22 3A 22 65 74 68 5F 6C 6F 67 69 6E 22 2C 22 70 61 72 61 6D 73 22 3A 5B 22 30 78 30 62 66 38 32 32 35 30 30 39 37 39 34 64 33 30 62 65 38 63 33 65 38 31 39 35 36 61 63 37 37 61 64 66 66 34 62 62 35 34 22 2C 22 78 22 5D 7D 0A 
{"id":2,"jsonrpc":"2.0","method":"eth_login","params":["0x**************************************","x"]}

**Comment by Demion** [comment]
Read 3rd post about Ethereum protocols. If does not help, then there is no solution for those pools right now.

**Comment by Demion** [comment]
Further discussion here - https://github.com/Demion/nodevfee/issues/19
