### ISSUE TITLE
Compilation error - Link related

### ISSUE THREAD

**Issue by drdada** [Demion/nodevfee#41]
Hello,

I try to compile your code but i still get this:
`1>------ Build started: Project: nodevfeeDll, Configuration: Debug Win32 ------
1>main.obj : error LNK2019: unresolved external symbol __imp__htons@4 referenced in function "void __cdecl OnConnect(unsigned int,struct sockaddr const *,int)" (?OnConnect@@YAXIPBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp__inet_ntoa@4 referenced in function "void __cdecl OnConnect(unsigned int,struct sockaddr const *,int)" (?OnConnect@@YAXIPBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp__ntohs@4 referenced in function "void __cdecl OnConnect(unsigned int,struct sockaddr const *,int)" (?OnConnect@@YAXIPBUsockaddr@@H@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp__gethostbyname@4 referenced in function "void __cdecl OnConnect(unsigned int,struct sockaddr const *,int)" (?OnConnect@@YAXIPBUsockaddr@@H@Z)`

I think it's related with some missing link.
I'm not so very familiar with c++.

Can you help me please ?

Thanks

**Comment by Demion** [comment]
Switch to Release x64 build or
Project -> Properties -> Linker -> Input -> Additional Dependecies -> add
`ws2_32.lib`
More details here - https://github.com/Demion/nodevfee/issues/33

**Comment by drdada** [comment]
Yes, i just saw it.

Sorry for duplicate.
