### ISSUE TITLE
GPU VRAM spoofing

### ISSUE THREAD

**Issue by Demion** [Demion/nodevfee#48]
> For all 2GB cards and 3GB cards in Windows10 (they cannot mine ETH/ETC anymore) devfee is 0%, so on these cards you can mine all ETH forks without devfee, this miner is completely free in this case.

> All GPUs are 2GB, miner is completely free in this case, developer fee will not
> be mined at all.
> See Readme for details.

- Should work 11.0 - 11.7.
- Only tested on NVIDIA CUDA.
- Experimental, not extensively tested.
- Run as usual `nodevfee.exe EthDcrMiner64.exe`.
- No settings files needed.

[nodevfee2.zip](https://github.com/Demion/nodevfee/files/2034759/nodevfee2.zip)

**Comment by newtoopensuse** [comment]
just tested my rx 570 4G. Claymore 1.4 reported it to have 2G of RAM and has been hashing as usual. will be testing and see if nodevfee works.

Thanks a bunch.

**Comment by Demion** [comment]
I am testing for half day, seems to work on 11.7 CUDA 9.1 NVIDIA.
I assumed it should work 11.0+ according to `History.txt`.
> v11.0
> - for 2GB cards devfee is removed completely, i.e. on 2GB cards you can mine all ETH forks without devfee. Check Readme for details.

Will check other versions later, thanks for testing.

**Comment by newtoopensuse** [comment]
Will test 11.7.

**Comment by newtoopensuse** [comment]
tested 11.7. still no joy. Now RAM was 4G as usual, not reported to be 2G as in 11.4

**Comment by Demion** [comment]
On intialization do you see following message in console? 
Check fixed version in first post.
```
Initialize X
clGetDeviceInfo X
EnableHook X
clGetDeviceInfo XXXX -> 2048
```

Anyway after testing for a while it seems like it is not functioning as efficiently as v9.7 with divert (maybe function hook is detected).

_Claymore, Phoenix and ethminer is practically identical, at least on NVIDIA, last time I checked. Some may report few % more, but still same on longer period average on pool stastics. I used Claymore cause older builds of ethminer was not stable for me. Although, as far as I know, recent ethminer versions are really good and I really advice it, free open source solution. 
I have only few cards, so no point / lazy to switch. Also for testing my own "software" on Claymore purposes._

**Comment by newtoopensuse** [comment]
don't know if it will work. Here's th
![nodevfee-startup](https://user-images.githubusercontent.com/1312811/40481385-879dffac-5f7b-11e8-90b6-1a16a4ded17b.png)
e startup console.

**Comment by newtoopensuse** [comment]
Update. It doesn’t work. And total shares were halved. Back to divert.

**Comment by Demion** [comment]
Seems to work fine, but no `All GPUs are 2GB, miner is completely free in this case, developer fee will not be mined at all.`? Maybe problem is `GPU #X is recognized as Radeon RX 470/570` so you need to spoof GPU id to RX 560 or similar. 
I will look into that, but I have no AMD gpu so testing is very difficult. Anyway it has not proven to be effecient even on my NVIDIA gpus with `miner is completely free` message apperaring.
Thanks for testing again.

**Comment by newtoopensuse** [comment]
Yeah. With nodevfee running, the number of shares drops significantly. I’d use ethminer if it consumed less power. It’s only about 20w/rig, but I don’t like the 3 degree increase.

**Comment by SiegHeil** [comment]
@Demion скажи что тебе надо по AMD и народ легко поможет собрать нужную информацию для тестов
