### ISSUE TITLE
disconnect from nanopool because nodevfee

### ISSUE THREAD

**Issue by peshunski** [Demion/nodevfee#5]
For the first hours it works without any issues but after a while, Nanopool seems to disconnect the rig showing a connection error:

ETH: Stratum - Cannot connect to eth-eu1.nanopool.org:9999
ETH: Stratum - Failed to connect, retry in 20 sec...

**Comment by stevengdev** [comment]
Considering Claymore and nanopool seem to have a thing, I wouldn't be surprised if they have some back end type thing working together. Ethermine seems stable after about 5hrs and counting. I would also strongly suggest you use Claymore10 with NoDevFee 0.2.1.  I had difficulty with 0.2.2b, but 0.2.1 works as expected.

**Comment by Narratheon** [comment]
Nope, whatever you are doing you seem to do it wrong. Nodevfee works perfectly fine with Nanopool, Claymore 10 and 0.2.1.

**Comment by Demion** [comment]
Users report some actual efficiency decrease starting from version 10.1 and later (might be some hidden protection). Seems to work fine on 9.7 and ethermine for me.

**Comment by Narratheon** [comment]
I am using Claymore 10 and NoDevFee 0.2.2 and it works fine. The efficiency decrease is global as the network hashrate and difficulty has increased by I think 300%. This has nothing to do with your great work.

**Comment by PeshBG** [comment]
10.5 here 0.2.2b all fine so far :) nanopool 188 + PASL @ 2250

**Comment by Demion** [comment]
Further discussion here - https://github.com/Demion/nodevfee/issues/19
