### ISSUE TITLE
Slowed down hashrate with claymore v10.0

### ISSUE THREAD

**Issue by ThatPR** [Demion/nodevfee#7]
Hi, I am dual mining ETH + DCR on two same rigs. I run this dev fee remover on one of them, and after that, current hashrate dropped about 20-25Mh/s down. 
Which version of miner I should use? 
Thanks

**Comment by Narratheon** [comment]
I can confirm it works perfectly fine with Nanopool.org, Claymore 10 and 0.2.1.

**Comment by ThatPR** [comment]
Do you mine eth only or dual?

**Comment by Narratheon** [comment]
Dual, ETH+SIA. SIA is not very rewarding at this time, because of the bug that was implemented with the hard fork at block 136.000, though.

And I think I am using 0.2.2.
