### ISSUE TITLE
Failed to work due to the restart

### ISSUE THREAD

**Issue by jaegerstar** [Demion/nodevfee#9]
My claymore could be freezed if I hadn't restart it every 30 minutes because of some unknown troubles.However nodevfee seems failed to do its work because of that. Any idea how to avoid that ?

**Comment by jaegerstar** [comment]
Found the fix. As long as I remove the _-mode 1_ , everything is fine. Maybe it's a hidden bug I suppose ?

**Comment by Demion** [comment]
Claymore log will think that it mines to their devfee wallet it is normal.
If you want to see actual modified packets sent to pool with your wallet - create empty text file nodevfeeLog.txt
